apiVersion: apps/v1
kind: Deployment
metadata:
  name: king
spec:
  replicas: 1
  selector:
    matchLabels:
      app: king
  template:
    metadata:
      labels:
        app: king
    spec:
      containers:
      - image: okteto.dev/kin:latest
        name: king
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "85417281-71d3-44a2-bca0-466ca3afb726"
        - name: Vless_Path
          value: "/vl5dg"
        - name: Vmess_UUID
          value: "430cbad5-aa8e-44e3-ab5e-97255192ccd1"
        - name: Vmess_Path
          value: "/vmv8hb"
        - name: Share_Path
          value: "/v2link"
