apiVersion: apps/v1
kind: Deployment
metadata:
  name: kin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kin
  template:
    metadata:
      labels:
        app: kin
    spec:
      containers:
      - image: okteto.dev/kin:latest
        name: kin
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4853783d-56a2-4f38-ab54-e9d6e4395848"
        - name: Vless_Path
          value: "/vlyyyyy"
        - name: Vmess_UUID
          value: "22775dce-b934-4f99-85df-07d4cf77664c"
        - name: Vmess_Path
          value: "/vm99999"
        - name: Share_Path
          value: "/v2link"
